### ISSUE TITLE
Allow more flexibility with Props for stencil.stories generation 

### ISSUE THREAD

**Issue by dexster** [dutscher/stencil-storybook#10]
The stencil-to-storybook generation is restrictive and requires the following criteria in order to generate stencil-stories.ts with all the props added:

Props must have jsdoc comments
The comments must be on one line
The prop names must be lowercase

Is there a reason for this or can I submit a PR to allow scenarios like this:

```
/**
 * Specify size limit in Kb
 * */
@Prop() maxFileSize
```

and also for props with no comments.

**Comment by dexster** [comment]
or... can we not use the generated json docs from Stencil to build the template?

**Comment by dutscher** [comment]
the stencil-to-storybook generator is much faster then the generated json from stencil it self. 
i fix the regexp that your code will also match! thanks for the suggestion!
cheers

**Comment by dutscher** [comment]
Here is the PR https://github.com/dutscher/stencil-storybook/pull/11
![image](https://user-images.githubusercontent.com/14682/120638472-739d4500-c470-11eb-994b-add846e26fe7.png)
![image](https://user-images.githubusercontent.com/14682/120641555-04295480-c474-11eb-84ff-7462dc996c2b.png)

**Comment by dutscher** [comment]
it's done ;) can you confirm?

**Comment by dexster** [comment]
Thanks for this.

I'm still wondering about the stencil generator. I'm using the stencil-to-storybook script but instead of reading each file line by line, I just import and parse the stencil generated components.json to generate defaultJSON. 

Stencil also generates the components.json very quickly so I'm not seeing a slowdown in the build.

My reasoning is that stencil generates a well documented json structure based on document interfaces so it is quite robust and also saves us from parsing all the files with regex. What do you think?

It's currently working very well in my build.

**Comment by dutscher** [comment]
hi dexster,
with 1 component is the stencil build fast but when you have a design system up to 50 components its gettin slower and slower.
the next reason is that the component json is build once on only production. there is no possibility to get the json on development.
and thanks for using my repo 🗡️ 

cheers
