### ISSUE TITLE
Creating Storybook stories in combination with slots

### ISSUE THREAD

**Issue by SuperSchek** [dutscher/stencil-storybook#12]
In the example story there is a section about slots that I don't quite understand:
```
export const Slots = setupComposition(
  `<slot's />`,
  () => h`
  ${['Slot eins', 'Slot dva'].map((slot) => h`${Story.tplComposition({ slot })}<br>`)}
`,
);
```
I've played around with it but I don't seem to be able to get it working. The first parameter is supposed to be the name of slot you want to use? Any elaboration would be greatly appreciated.

My component:
```
<Host
  onClick={this.handleClick}
>
  <TagType
    {...attributes}
    class={this.buttonClasses}
    disabled={disabled}
    onFocus={this.onFocus}
    onBlur={this.onBlur}
    {...inheritedAttributes}
  >
    <slot name="left" />
    <slot name="label">
      <span>{label}</span>
    </slot>
    <slot name="right" />
  </TagType>
</Host>
```
What would I have to pass to `setupComposition` in order to render some lit-html in the `left` slot?

**Comment by dutscher** [comment]
well :D its hard with lithtml between.

`Story.tplComposition({ slot })}` slot needs a string or a h`` wrapped when there is reactive stuff inside.

and your slot value should be:
`const slot = '<div slot="left">left</div><div slot="right">right</div>'`
https://github.com/dutscher/stencil-storybook/blob/5fa2ec4ec0c3b5159e832bcc49e4d496c6d83656/src/components/my-component/my-component.stories.ts#L40

edit: other tip, look inside the generated `stencil-stories.ts` file. there is a tpl method. this will help you to get what i mean ;)
https://github.com/dutscher/stencil-storybook/blob/master/src/components/my-component/stencil-stories.example.ts

cheers

**Comment by SuperSchek** [comment]
@dutscher This was exactly what I needed! Now I can finally document my slots in peace.

My stories generated by `setupComposition` are not configured to handle controls. Is there a way to get this working or is that expected behavior? 

Thanks for the help!
