### ISSUE TITLE
Are they any plans with licensing?

### ISSUE THREAD

**Issue by mohab-mohamed** [dutscher/stencil-storybook#13]
Not sure if any contributors are still active but found this to be a cool project and I was wondering if there were any plans on adding a license. Would be nice to play with but cannot find any license on the repo and this [https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license] says I'm only really allowed to look, which scares me off a bit. Is this done purposely or are there plans to add an open-source license?

Thanks for the time!

**Comment by dutscher** [comment]
look into the package.json ;)

**Comment by millbj92** [comment]
I'm sure they'd be happy to have someone contribute a LICENSE.md file to the repo :)

**Comment by dutscher** [comment]
file is there ;) 

cheers
