### ISSUE TITLE
Multiple dists

### ISSUE THREAD

**Issue by nccandiotti** [dutscher/stencil-storybook#14]
Hi :)

Less of an ‘issue’ and more of a question. I was wondering if you had any suggestions on creating multiple dists. I have some ‘extra’ components that i’ve made specifically to have as a sandbox area on storybook, so I want them in the dist for the storybook build, but I don’t want them in the dist-stencil that I am publishing on the npm package. Was wondering if you had any ideas or suggestions. 

Thank you

**Comment by dutscher** [comment]
hi there, i solved this issue with one dist which ich filled up with a pre storybook task.
for example: $ npm run copy:files:into:dist && build-storybook --quiet --output-dir ./dist/storybook

cheers

**Comment by nccandiotti** [comment]
Thank you so much I will give this a try!
