### ISSUE TITLE
Does it work with latest Stencil v1?

### ISSUE THREAD

**Issue by markcellus** [dutscher/stencil-storybook#3]
Hello @dutscher and thank you so much for creating this package! :heart: 

I see that it supports Stencil v2 but our organization can't quite move to v2 just yet, so we're on the latest version of v1. Would this package work with the latest v1?

Thanks for any information.

**Comment by dutscher** [comment]
storybook runs alone and stencil is connected via proxy. so i promise you that your "old" stencil will work.
give it a try, clone and set down the stencil version in package.json. the sample component and scss should run also under older version.

cheers

**Comment by markcellus** [comment]
Ah okay, that's great. I'll give it a try!

**Comment by dutscher** [comment]
please let me know if it really works :)
