### ISSUE TITLE
chromatic setup

### ISSUE THREAD

**Issue by evaneus** [dutscher/stencil-storybook#7]
Thanks for this - we're using it for our project.
Having an issue with chromatic though, in that the stencil [app].esm.js and css files are not in `dist-storybook`
Locally the proxy.js works to replace those urls, but on chromatic we get 404s
We're looking into it but want to ask here to see if this should work and if we're missing something?

**Comment by dutscher** [comment]
when you build storybook you should copy the stencil dist (which should build before storybook) with the param -s (--static-dir ./dist-stencil/stencil-storybook").

1. is your stencil dist inside your storybook dist?
2. has the storybook webpack dist the correct path to stencil due prod build? https://github.com/dutscher/stencil-storybook/blob/b51be3d1d22fe7c291398d5e9ab12ea68e4ee813/.storybook/main.js#L13
3. maybe you can share something where i can assists you

cheers
