### ISSUE TITLE
Can't resolve components in my project

### ISSUE THREAD

**Issue by SuperSchek** [dutscher/stencil-storybook#8]
Hi there,

First of all, thanks a lot for this setup. It's great!

I am running into a problem where my components can't be resolved when I try to import them in my ionic project.

Some more info:
- I am building my Stencil project with `yarn build:stencil`
- I ran `yarn link` in my Stencil project
- I ran `yarn link <project-name>` in my ionic vue project
- I am importing the web component with 
```javascript
import { MyComponent } from "<project-name>"
```

When  I load the page, I see the following error in the console: `Failed to resolve component: MyComponent`

Am I missing something here

**Comment by dutscher** [comment]
can you share your index file of your build?

cheers
