### ISSUE TITLE
Module '"../index"' has no exported member 'splitByWhiteSpace'.

### ISSUE THREAD

**Issue by PepeTrigo** [dutscher/stencil-storybook#9]
Hello,

Thanks a lot for the setup. Looks great!

I tried starting it but its tying to import something that its not being exported

https://github.com/dutscher/stencil-storybook/blob/e2bc66d6af002d6b94911abbe43cb91d61f31524/src/utils/tests/spec-helper.ts#L2

**Comment by dutscher** [comment]
hi pepetrigo, 
the test was broken, now the tests are green and the start task run also like a charm.
good you try this on your machine?

cheers

**Comment by PepeTrigo** [comment]
Works like a charm in my machine now.

Thanks a lot for the great work!

Cheers
